name: "$(SourceBranchName)+$(BuildID)"

parameters:
  - name: internal_envs
    type: boolean
    default: true
    displayName: Internal Environments (internal-dev, internal-dev-sandbox, internal-qa, internal-qa-sandbox, ref)
  - name: external_envs
    type: boolean
    default: true
    displayName: External Environments (dev, sandbox, int, prod)
  - name: selection
    type: string
    default: diff
    values:
      - diff
      - all
    displayName: JWKS Selection (diff or all time)
  - name: check_mode
    type: boolean
    default: True
    displayName: Run ansible with --check (always the case for branch != main)

pr: # Only trigger on PRs targeting main
  branches:
    include:
      - main

trigger: # Don't trigger on updates to any branch
  branches:
    exclude:
      - '*'

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      endpoint: NHSDigital

extends:
  template: ./components/deploy-jwks.yml
  parameters:
    internal_envs: ${{ parameters.internal_envs }}
    external_envs: ${{ parameters.external_envs }}
    selection: ${{ parameters.selection }}
    check_mode: ${{ parameters.check_mode }}
