parameters:
  - name: internal_envs
    type: boolean
  - name: external_envs
    type: boolean
  - name: selection
  - name: check_mode
    type: boolean

stages:

  - template: ./deploy-jwks-all.yml
    parameters:
      internal_envs: ${{ parameters.internal_envs }}
      external_envs: ${{ parameters.external_envs }}
      selection: ${{ parameters.selection }}

      # non-main branches ALWAYS run in check mode
      ${{ if ne(variables['Build.SourceBranch'],'refs/heads/main') }}:
        check_mode: 1
      ${{ if eq(variables['Build.SourceBranch'],'refs/heads/main') }}:
        ${{ if parameters.check_mode }}:
          check_mode: 1
        ${{ if not(parameters.check_mode) }}:
          check_mode: 0
